# .appveyor.yml

# Build version
version: '1.0.{build}'

# Use the latest available toolchain
image: Visual Studio 2019

# fetch repository as zip archive
shallow_clone: true

# PRs do not increment the build number
pull_requests:
  do_not_increment_build_number: true

# Build configurations
configuration:
  - Debug
  - Release

# Default environment variables
environment:
  _IS_BUILD_CANARY: false
  _RELEASE_NAME: vgmstream
  # Use Python 3.x
  PYTHON: "C:\\Python38-x64"
  PYTHON_VERSION: "3.8.x"
  PYTHON_ARCH: "64"

# Prepare Cpp environment
before_build:
  - cmd: |
      set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - ps: |
      if ($env:APPVEYOR_REPO_TAG -eq "true" -and $env:APPVEYOR_REPO_TAG_NAME) {
        $env:APPVEYOR_BUILD_VERSION = $env:APPVEYOR_BUILD_VERSION.Substring(0,$env:APPVEYOR_BUILD_VERSION.LastIndexOf('.')) + ".0"
        $env:_RELEASE_NAME = $env:_RELEASE_NAME + "-v" + $env:APPVEYOR_BUILD_VERSION
      } else {
        $env:_RELEASE_NAME = $env:_RELEASE_NAME + "-Canary"
        $env:APPVEYOR_REPO_TAG_NAME = "canary"
        $env:_IS_BUILD_CANARY = "true"
      }

build_script:
  - cmd: |
      md .dist\build\x86-%CONFIGURATION%
      cd .dist/build/x86-%CONFIGURATION%
      cmake -G "Visual Studio 16 2019" -A Win32 -D_DLL_VERSION="%appveyor_build_version%" -DCMAKE_BUILD_TYPE="%CONFIGURATION%" -DCMAKE_BINARY_DIR=".dist/build/x86-%CONFIGURATION%" --config %CONFIGURATION% -DCMAKE_INSTALL_PREFIX=".dist/build/x86-%CONFIGURATION%/bin" -DUSE_FFMPEG=ON -DUSE_FDKAAC=OFF -DUSE_MPEG=OFF -DUSE_VORBIS=OFF -DUSE_MAIATRAC3PLUS=OFF -DUSE_G7221=OFF -DUSE_G719=OFF -DUSE_ATRAC9=OFF -DUSE_CELT=OFF -DBUILD_CLI=OFF -DBUILD_FB2K=OFF -DBUILD_WINAMP=OFF -DBUILD_XMPLAY=OFF -DBUILD_AUDACIOUS=OFF ../../..
      cmake --build . --config %CONFIGURATION%

# Do not run unit tests
test: off

# Package artifacts
artifacts:
  - path: .dist\build\x86-%CONFIGURATION%\bin
    name: ${_RELEASE_NAME}_${CONFIGURATION}
    type: zip

# Create a GitHub release for every tag
deploy:
  # Deploy only when new tags are pushed
  - provider: GitHub
    tag: ${appveyor_repo_tag_name}
    release: ${_RELEASE_NAME}
    artifact: ${_RELEASE_NAME}_${CONFIGURATION}
    auth_token:
      secure: SXUyBqg8+wl9fn3xHV2Br0xDH65EyPAnFwJbwcg94wIesv9osQEefC3zxu9iDTUh
    on:
      _IS_BUILD_CANARY: false
  # Deploy on each commit
  - provider: GitHub
    tag: ${appveyor_repo_tag_name}
    release: ${_RELEASE_NAME} v${appveyor_build_version}
    artifact: ${_RELEASE_NAME}_${CONFIGURATION}
    prerelease: true
    force_update: true
    auth_token:
      secure: SXUyBqg8+wl9fn3xHV2Br0xDH65EyPAnFwJbwcg94wIesv9osQEefC3zxu9iDTUh
    on:
      _IS_BUILD_CANARY: true
    description: |
      This is a canary build. Please be aware it may be prone to crashing and is NOT tested by anyone. Use this build AT YOUR OWN RISK!
